### ISSUE TITLE
Better support for filling a bucket already partially full and/or emptying one

### ISSUE THREAD

**Issue by Cervator** [Terasology/Fluid#10]
May belong more in JS or TTA, although it would be nice to have such utility here.

Can "top off" a portable herbalism station in TTA now and end up with a partially filled bucket. But then can't fill said bucket from a water source :-)

Probably that should be doable if you have a partially filled bucket _or_ there should be an easy way to dump the contents of a bucket. Maybe we can standardize a click system for that. Left click dumps, right click fills? Or right click on anything other than a water source dumps/fills the target if appropriate?

The portable herbalism station has a slot in it for water while the sifting table can be filled by right clicking it while holding a full bucket.

Again pinging @Josharias and @xrtariq2594

**Comment by Josharias** [comment]
Yeah, these kind of issues are why I have hesitated doing anything to intricate with fluid container volumes.. Filling back up from a water source seems easily doable from a JS perspective.  Dumping out though.... not as simple.

**Comment by Cervator** [comment]
Doesn't have to be dumping back into a fluid source in the world :-) Just `<action>` -> bucket is now empty! Fluid magically disappeared into a dimensional pocket, never to be seen again.

May be a little hacky but easy for now

**Comment by nihal111** [comment]
I've implemented emptying of container after drinking here- https://github.com/Terasology/Thirst/pull/2, much like how you mentioned in the comment above @Cervator :wink:

**Comment by Cervator** [comment]
Thanks @nihal111 :-)

After merging https://github.com/Terasology/Thirst/pull/2 this is *better* but needs just a bit more tweaking. I think it is just looking around at a few fluid container prefabs to make sure they're registered right. Stuff I noticed:

* The wooden *cup* works seemingly as expected - if you right click while facing a nearby block you'll empty the cup, if you do not have a nearby block highlighted it'll make the player drink
* The wooden bucket doesn't appear to be activated for the same logic yet (can't empty it, can't drink it)
* Neither appears able to top off a `fluidtank` from JS - if I fill it up to one bucket from max, then drop in a cup's worth of water, another bucket cannot partially empty into the tank

My expectation would be that the fluid tank would also be able to take a partial bucket, like the herbalism station. Which I admittedly forgot to retest. Again probably just something simple isn't enabled somewhere.
