### ISSUE TITLE
Custom fluid rendering into a container doesn't work (in TTA at least)

### ISSUE THREAD

**Issue by Cervator** [Terasology/Fluid#4]
See https://github.com/MovingBlocks/Terasology/issues/1802 for details. Minor validation is now in place to catch the crash, but the asset parsing needs to be fixed and hardened more properly (or possibly the asset definition needs to be tweaked instead?)

Pinging @MarcinSc @flo @Josharias to see if one of you could get to it sometime - _probably_ a fairly easy fix for one of you :-)

**Comment by Cervator** [comment]
Does seem to work in JoshariasSurvival. Do we have two overlapping implementations somewhere or just differing assets?

**Comment by Josharias** [comment]
Different implementations.  I am utilizing ItemRendering module to fill
buckets in Josharias survival.

**Comment by Cervator** [comment]
Expecting ItemRendering covers a "wider" implementation (than just fluids) could we update TTA (and any other users, if any?) to use that instead and delete the special handling in the Fluid module? If it doesn't work anyway and isn't needed anymore ... :-)

**Comment by Cervator** [comment]
Fixed by #7
